name: daydream
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.3.3
  image_picker: ^1.1.2
  intl: ^0.19.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.2
  url_launcher: ^6.3.1
  http: ^1.2.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/daydream.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/LOGO2.png
